game: 
  name: Tower Defence
  fps: 60
  levels: 1
  level_complete_reward: 100

  # game screen parameters
  screen:
    rows: 15
    cols: 15
    tile_size: 48
    side_panel: 300
    width: 720
    height: 720
    color: grey100
    images:
      heart: src/assets/images/gui/heart.png
      coin: src/assets/images/gui/coin.png
      logo: src/assets/images/gui/logo.png

  # game world parameters
  world:
    map_image: src/assets/levels/level.png
    world_data: src/assets/levels/level.tmj
    money: 650
    health: 50

  # button parameters
  button:
    buy_turret:
      image: src/assets/images/buttons/buy_turret.png
      coord: 
        - 750
        - 120
    cancel:
      image: src/assets/images/buttons/cancel.png
      coord:
       - 770
       - 180
    upgrade:
      image: src/assets/images/buttons/upgrade_turret.png
      coord:
        - 725
        - 180
    begin:
      image: src/assets/images/buttons/begin.png
      coord: 
       - 780
       - 300
    restart:
      image: src/assets/images/buttons/restart.png
      coord:
       - 310
       - 300
    fast_forward:
     image: src/assets/images/buttons/fast_forward.png
     coord:
      - 770
      - 300

  # turret parameters
  turret:
    cursor_turret: src/assets/images/turrets/cursor_turret.png
    turret_spritesheets:
      - src/assets/images/turrets/turret_1.png
      - src/assets/images/turrets/turret_2.png
      - src/assets/images/turrets/turret_3.png
      - src/assets/images/turrets/turret_4.png
    animation_steps: 8
    animation_delay: 50
    levels: 4
    buy_cost: 200
    upgrade_cost: 100
    kill_reward: 1
    level_reward: 100
    damage: 10
    upgrades:
        # level 1 
      - range: 90
        cooldown: 1500
        # level 2
      - range: 110
        cooldown: 1200
        # level 3
      - range: 125
        cooldown: 1000
        # level 4
      - range: 150
        cooldown: 900
        
  # enemy parameters
  enemy:
    health: 100
    spawn_cooldown: 400
    types:
      weak: 
        health: 10
        speed: 2
        image: src/assets/images/enemies/enemy_1.png
      medium: 
        health: 15
        speed: 3
        image: src/assets/images/enemies/enemy_2.png
      strong:
        health: 20
        speed: 4
        image: src/assets/images/enemies/enemy_3.png
      elite:
        health: 30
        speed: 6
        image: src/assets/images/enemies/enemy_4.png
    levels:
        # level 1
      - weak: 15
        medium: 0
        strong: 0
        elite: 0
        # level 2
      - weak: 30
        medium: 0
        strong: 0
        elite: 0
        # level 3
      - weak: 20
        medium: 5
        strong: 0
        elite: 0
        # level 4
      - weak: 30 
        medium: 15
        strong: 0
        elite: 0
        # level 5
      - weak: 5
        medium: 20
        strong: 0
        elite: 0
        # level 6
      - weak: 15
        medium: 15
        strong: 4
        elite: 0
        # level 7
      - weak: 20 
        medium: 25
        strong: 5
        elite: 0
        # level 8
      - weak: 10
        medium: 20
        strong: 15
        elite: 0
        # level 9
      - weak: 15
        medium: 10
        strong: 5
        elite: 0
        # level 10
      - weak: 0
        medium: 100
        strong: 0
        elite: 0 
        # level 11
      - weak: 5
        medium: 10
        strong: 12
        elite: 2
        # level 12
      - weak: 0 
        medium: 15
        strong: 10
        elite: 5
        # level 13
      - weak: 20
        medium: 0 
        strong: 25
        elite: 10
        # level 14
      - weak: 15
        medium: 15
        strong: 15
        elite: 15
        # level 15
      - weak: 25
        medium: 25
        strong: 25
        elite: 25