game: 
  screen:
    rows: 15
    cols: 15
    tile_size: 48
    side_panel: 300
    width: 720
    height: 720
    color: grey100
  fps: 60
  name: Tower Defence
  turret:
    animation_steps: 8
    animation_delay: 50