agent:
  init_gamma: 0.9
  init_eps: 0.3
  end_eps: 0.05
  eps_decay: 1000
  max_memory: 100
  tau: 0.005
model:
  lr: 1.0e-5
  batch_size: 16
  architecture:
    encoder: resnet18
  loss_function: 
    name: mseloss
  optim: 
    name: adam
  checkpoint_path: 'checkpoints_long'