agent:
  init_gamma: 0.9
  init_eps: 0
  max_memory: 10000
model:
  lr: 1.0e-5
  batch_size: 16
  architecture:
    encoder: resnet18
  loss_function: 
    name: mseloss
  optim: 
    name: adam
  checkpoint_path: 'model_checkpoints'